### ISSUE TITLE
create test harness

### ISSUE THREAD

**Issue by guano** [byu-oit-appdev/byu-event-cacher-lambda-dynamodb#3]
make scripts.test.js
(look at map-publish-lambda for an intro)

we want the test to run the lambda and make sure it receives and returns proper data

**Comment by guano** [comment]
make sure we know what an sns event looks like because that will be the input

**Comment by johnrb2** [comment]
I have created the test.js file with sample code from the map-publish-lambda in it that has been commented out.

**Comment by johnrb2** [comment]
i moved the test.js into scripts directory
