### ISSUE TITLE
configure github project

### ISSUE THREAD

**Issue by guano** [byu-oit-appdev/byu-event-cacher-lambda-dynamodb#5]
master branch protected
AFTER circleci, can only merge when passing tests
turn off wiki, etc

**Comment by guano** [comment]
means we need to learn how to branch properly

**Comment by guano** [comment]
Done, except we need circleCI to be performing tests and then protect the main branch against the success of those tests

**Comment by johnrb2** [comment]
Completed learning about feature branch workflow
